version: '3'

services:
  rbt:
    build: .
    container_name: rbt
    restart: always
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELGRAM_CHAT_GROUP_ID: ${TELGRAM_CHAT_GROUP_ID}
      CORE_ADDRESS: ${CORE_ADDRESS}
      ROS_API_USER: ${ROS_API_USER}
      ROS_API_PASS: ${ROS_API_PASS}
      ROS_API_PORT: ${ROS_API_PORT}